apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/forms
namespace: development
commonLabels:
  app: forms
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: forms-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.forms:v5.4.0
#    - op: replace
#      path: /spec/template/spec/volumes/0
#      value:
#        name: forms-volume-config
#        csi:
#          driver: secrets-store.csi.k8s.io
#          readOnly: true
#          volumeAttributes:
#            secretProviderClass: "forms-secret-config"
- target:
    group: secrets-store.csi.x-k8s.io
    version: v1
    kind: SecretProviderClass
    name: forms-secret-config
  patch: |-
    - op: replace
      path: /spec/parameters
      value: 
        objects:  |
          - objectName: "forms-secret-config-development"
            objectType: "secretsmanager"
            jmesPath:
            - path: formssecretconfig
              objectAlias: appsettings.json
- target:
    version: v1
    kind: Secret
    name: forms-secret-config
  patch: |-
    - op: replace
      path: /data/config.json
      value: ewogICJhdXRob3JpdHkiOiAiaHR0cDovLzIwLjEyMS45Mi4xNzkvaWRwIiwKICAiY2luY2h5Um9vdFVybCI6ICJodHRwOi8vMjAuMTIxLjkyLjE3OSIsCiAgImNsaWVudElkIjogImNpbmNoeV9tZXRhX2Zvcm1zIiwKICAicmVkaXJlY3RVcmkiOiAiaHR0cDovLzIwLjEyMS45Mi4xNzkvbWV0YWZvcm1zIgp9
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: forms-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-forms-app
