apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/base
namespace: <<namespace>>
commonLabels:
  app: base
  env: <<namespace>>
patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: cinchy-environment-settings
  patch: |-
    - op: replace
      path: /data/encryptionkey
      value: N0VBRUFGQkUxMTJGMDE2QTk4MjFBQjg3NjZEQkU3QkE5NjJFMTNBN0ZDRkNGN0U4QzVFMkM4QTgwMTY5MDg2Mg==
    - op: replace
      path: /data/url
      value: <<application_url>>
    - op: replace
      path: /data/connectionspassword
      value: JHJIMjR4RHB3eU16
    - op: replace
      path: /data/workerpassword
      value: JHJIMzR4RnB3eU16
    - op: replace
      path: /data/eventlistenerpassword
      value: JHJINjR4UnB3eU16
    - op: replace
      path: /data/maintenancepassword
      value: JHJINTV4WnB3eU16
- target:
    version: v1
    kind: Namespace
    name: <ns>
  patch: |-
    - op: replace
      path: /metadata/name
      value: <<namespace>>
- target:
    version: "security.istio.io/v1beta1"
    kind: "PeerAuthentication"
    name: "ns-peerauthentication"
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: <<namespace>>
- target:
    version: "v1"
    kind: "Secret"
    name: "opensearch-credentials"
  patch: |-
     - op: replace
       path: /data/password
       value: <<opensearch_admin_user_password_base64>>
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: VirtualService
    name: cinchy-virtualservice
  patch: |-
    - op: replace
      path: /spec/hosts/0
      value: "<<host_name>>"

    - op: replace
      path: /spec/http/0/route/0/destination/host
      value: "connections-service.<<namespace>>.svc.cluster.local"
    - op: replace
      path: /spec/http/0/rewrite/uri
      value: "/"
    - op: replace
      path: /spec/http/0/match/0/uri/prefix
      value: "<<application_path>>/connections/"
    - op: replace
      path: /spec/http/0/match/1/uri/prefix
      value: "<<application_path>>/connections"

    - op: replace
      path: /spec/http/1/route/0/destination/host
      value: "event-listener-service.<<namespace>>.svc.cluster.local"
    - op: replace
      path: /spec/http/1/rewrite/uri
      value: "/"
    - op: replace
      path: /spec/http/1/match/0/uri/prefix
      value: "<<application_path>>/event-listener/"
    - op: replace
      path: /spec/http/1/match/1/uri/prefix
      value: "<<application_path>>/event-listener"

    - op: replace
      path: /spec/http/2/route/0/destination/host
      value: "forms-service.<<namespace>>.svc.cluster.local"
    - op: replace
      path: /spec/http/2/rewrite/uri
      value: "/"
    - op: replace
      path: /spec/http/2/match/0/uri/prefix
      value: "<<application_path>>/metaforms/"
    - op: replace
      path: /spec/http/2/match/1/uri/prefix
      value: "<<application_path>>/metaforms"

    - op: replace
      path: /spec/http/3/route/0/destination/host
      value: "idp-service.<<namespace>>.svc.cluster.local"
    - op: replace
      path: /spec/http/3/rewrite/uri
      value: "/"
    - op: replace
      path: /spec/http/3/match/0/uri/prefix
      value: "<<application_path>>/idp/"
    - op: replace
      path: /spec/http/3/match/1/uri/prefix
      value: "<<application_path>>/idp"

    - op: replace
      path: /spec/http/4/route/0/destination/host
      value: "web-service.<<namespace>>.svc.cluster.local"
    - op: replace
      path: /spec/http/4/rewrite/uri
      value: "/"
    - op: replace
      path: /spec/http/4/match/0/uri/prefix
      value: "<<application_path>>/"
    - op: replace
      path: /spec/http/4/match/1/uri/prefix
      value: "<<application_path>>"