apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/connections
namespace: development
commonLabels:
  app: connections
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: connections-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.connections.webapi:v5.1.0
    - op: add
      path: /spec/template/spec/volumes/-
      value: 
        name: connections-volume-redis-password
        secret:
          secretName: redis-redis-cluster
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: 
        name: connections-volume-redis-password
        readOnly: true
        mountPath: "/usr/share/redis/redis-redis-cluster"
- target:
    version: v1
    kind: Secret
    name: connections-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ew0KICAiQ2luY2h5Q2xpZW50U2V0dGluZ3MiOiB7DQogICAgIlVybCI6ICJodHRwczovL2NpbmNoeS5tZW51Y2l0eWFwcC5hbSIsDQogICAgIlVzZXJuYW1lIjogIiIsDQogICAgIlBhc3N3b3JkIjogIiIgIA0KICB9LA0KICAiQXBwU2V0dGluZ3MiOiB7DQogICAgIlRlbXBEaXJlY3RvcnkiOiAiL2FwcC90bXAiLA0KICAgICJNb2RlbCI6ICJDaW5jaHkiLA0KICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsNCiAgICAgICJCb290c3RyYXBTZXJ2ZXJzIjogImthZmthLWNsdXN0ZXIta2Fma2EtYm9vdHN0cmFwLmthZmthLnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIiDQogICAgfSwNCiAgICAiS2Fma2FDb25zdW1lclRocmVhZENvdW50IjogIjIiLA0KICAgICJLYWZrYU1lc3NhZ2VDb25zdW1lTXNMaW1pdCI6IDEwMCwNCiAgICAiS2Fma2FNZXNzYWdlQmF0Y2hDb25zdW1lTXNMaW1pdCI6IDIwMCwNCiAgICAiU3RvcmFnZVR5cGUiOiAiQXp1cmVCbG9iU3RvcmFnZSIsDQogICAgIkJhc2VQYXRoT3ZlcnJpZGUiOiAiIg0KICB9LA0KICAiQ29ubmVjdGlvblN0cmluZ3MiOiB7DQogICAgIlJlZGlzIjogInJlZGlzLXJlZGlzLWNsdXN0ZXIucmVkaXMuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OSINCiAgfSwNCiAgIkF6dXJlQmxvYlN0b3JhZ2VTZXR0aW5ncyI6IHsNCiAgICAiQ29ubmVjdGlvblN0cmluZyI6ICI8PGNvbm5lY3Rpb25zX2F6dXJlX2Jsb2Jfc3RvcmFnZV9jb25uX3N0cj4+IiwNCiAgICAiQ29udGFpbmVyIjogIm5vbnByb2QtY29ubmVjdGlvbnMiLA0KICAgICJCYXNlUGF0aCI6ICI8PGNvbm5lY3Rpb25zX3N0b3JhZ2VfYmFzZXBhdGg+PiINCiAgfSwNCiAgIlMzU2V0dGluZ3MiOiB7DQogICAgIkFjY2Vzc0tleSI6ICI8PGNvbm5lY3Rpb25zX3MzX2FjY2Vzc19rZXk+PiIsDQogICAgIlNlY3JldEFjY2Vzc0tleSI6ICI8PGNvbm5lY3Rpb25zX3MzX3NlY3JldF9hY2Nlc3Nfa2V5Pj4iLA0KICAgICJSZWdpb24iOiAiPDxhd3NfcmVnaW9uPj4iLA0KICAgICJCdWNrZXQiOiAiPDxjaW5jaHlfY29ubmVjdGlvbnNfczNfYnVja2V0Pj4iLA0KICAgICJCYXNlUGF0aCI6ICI8PGNvbm5lY3Rpb25zX3N0b3JhZ2VfYmFzZXBhdGg+PiIsDQogICAgIlNlcnZpY2VVUkwiOiAiPDxjb25uZWN0aW9uc19zM19zZXJ2aWNlX3VybD4+Ig0KICB9LA0KICAiQWxsb3dlZEhvc3RzIjogIioiLA0KICAiU2VyaWxvZyI6IHsNCiAgICAiTWluaW11bUxldmVsIjogew0KICAgICAgIkRlZmF1bHQiOiAiVmVyYm9zZSIsDQogICAgICAiT3ZlcnJpZGUiOiB7DQogICAgICAgICJNaWNyb3NvZnQiOiAiVmVyYm9zZSIsDQogICAgICAgICJTeXN0ZW0uTmV0IjogIlZlcmJvc2UiDQogICAgICB9DQogICAgfSwNCiAgICAiV3JpdGVUbyI6IFsNCiAgICAgIHsNCiAgICAgICAgIk5hbWUiOiAiQ29uc29sZSIsDQogICAgICAgICJBcmdzIjogew0KICAgICAgICAgICJmb3JtYXR0ZXIiOiAiU2VyaWxvZy5Gb3JtYXR0aW5nLkNvbXBhY3QuQ29tcGFjdEpzb25Gb3JtYXR0ZXIsIFNlcmlsb2cuRm9ybWF0dGluZy5Db21wYWN0Ig0KICAgICAgICB9DQogICAgICB9DQogICAgXQ0KICB9DQp9DQo=
- target:
    version: v1
    kind: Secret
    name: connections-secret-config
  patch: |-
    - op: replace
      path: /data/config.json
      value: ew0KICAgICJhdXRob3JpdHkiOiAiaHR0cHM6Ly9jaW5jaHkubWVudWNpdHlhcHAuYW0vaWRwIiwNCiAgICAiY2luY2h5Um9vdFVybCI6ICJodHRwczovL2NpbmNoeS5tZW51Y2l0eWFwcC5hbSIsDQogICAgImNsaWVudElkIjogImNpbmNoeV9jb25uZWN0aW9uc19leHBlcmllbmNlIiwNCiAgICAicmVkaXJlY3RVcmkiOiAiaHR0cHM6Ly9jaW5jaHkubWVudWNpdHlhcHAuYW0vY29ubmVjdGlvbnMiLA0KICAgICJtb2RlbCI6ICJDaW5jaHkiLA0KICAgICJkb21haW4iOiAiQ2luY2h5IiwNCiAgICAidXNlSHR0cHMiOiB0cnVlLA0KICAgICJzZXJ2ZXIiOiAiY2luY2h5Lm1lbnVjaXR5YXBwLmFtIiwNCiAgICAidmVyc2lvbiI6ICIxLjAuMCINCn0=
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: connections-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-connections-app
- target:
    group: kafka.strimzi.io
    version: v1beta2
    kind: KafkaTopic
    name: <environment>-connectionsjobcancellationrequests
  patch: |-
    - op: replace
      path: /metadata/name
      value: development-connectionsjobcancellationrequests
    - op: replace
      path: /metadata/namespace
      value: kafka
- target:
    group: kafka.strimzi.io
    version: v1beta2
    kind: KafkaTopic
    name: <environment>-connectionsjobqueue
  patch: |-
    - op: replace
      path: /metadata/name
      value: development-connectionsjobqueue
    - op: replace
      path: /metadata/namespace
      value: kafka
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: DestinationRule
    name: connections-destinationrule
  patch: |-
    - op: replace
      path: /spec/trafficPolicy/loadBalancer/consistentHash/httpCookie/name
      value: development-connections-canary
