apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/idp
namespace: development
commonLabels:
  app: idp
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: idp-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.idp:v5.1.0
    - op: add
      path: /spec/template/spec/volumes/-
      value: 
        name: idp-volume-redis-password
        secret:
          secretName: redis-redis-cluster
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: 
        name: idp-volume-redis-password
        readOnly: true
        mountPath: "/usr/share/redis/redis-redis-cluster"
- target:
    version: v1
    kind: Secret
    name: idp-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ew0KICAiQ29uZmlnU2V0dGluZ3MiOiB7DQogICAgIkFwcFNldHRpbmdzIjogew0KICAgICAgIkNpbmNoeVVyaSI6ICJodHRwczovLyIsDQogICAgICAiQ2VydGlmaWNhdGVQYXRoIjogIi9hcHAvY2luY2h5aWRlbnRpdHlzcnYucGZ4IiwNCiAgICAgICJDZXJ0aWZpY2F0ZVBhc3N3b3JkIjogIiIsDQogICAgICAiU0FNTENsaWVudEVudGl0eUlkIjogIiIsDQogICAgICAiU0FNTElEUEVudGl0eUlkIjogIiIsDQogICAgICAiU0FNTE1ldGFkYXRhWG1sUGF0aCI6ICIiLA0KICAgICAgIlNBTUxTU09TZXJ2aWNlVVJMIjogIiIsDQogICAgICAiU0FNTEVuY3J5cHRlZENlcnRpZmljYXRlUGF0aCI6ICIiLA0KICAgICAgIlNBTUxFbmNyeXB0ZWRDZXJ0aWZpY2F0ZVBhc3N3b3JkIjogIiIsDQogICAgICAiU0FNTFNpZ25DZXJ0aWZpY2F0ZVBhdGgiOiAiIiwNCiAgICAgICJTQU1MU2lnbkNlcnRpZmljYXRlUGFzc3dvcmQiOiAiIiwNCiAgICAgICJBY3NVUkxNb2R1bGUiOiAiIiwNCiAgICAgICJTdHNQdWJsaWNPcmlnaW5VcmkiOiAiaHR0cHM6Ly8vaWRwIiwNCiAgICAgICJNYXhSZXF1ZXN0SGVhZGVyc1RvdGFsU2l6ZSI6IDY1NTM2LA0KICAgICAgIk1heFJlcXVlc3RCdWZmZXJTaXplIjogNjU1MzYsDQogICAgICAiTWF4UmVxdWVzdEJvZHlTaXplIjogLTEsDQogICAgICAiTWFjaGluZUtleVhtbCI6ICIiLA0KICAgICAgIkRwQXBpS2V5UmluZ1BhdGgiOiAiIiwNCiAgICAgICJUbHNWZXJzaW9uIjogIjEuMiIsDQogICAgICAiQ2luY2h5QWNjZXNzVG9rZW5MaWZldGltZSI6ICIwLjAwOjMwOjAwIiwNCiAgICAgICJEYXRhQ2hhbmdlQ2FsbGJhY2tUaW1lb3V0IjogNywNCiAgICAgICJSZWZyZXNoQ2FjaGVUaW1lSW5NaW4iOiAxMCwNCiAgICAgICJEZWZhdWx0RXhwaXJhdGlvbkNhY2hlVGltZUluTWluIjogMzYwLA0KICAgICAgIkRCVHlwZSI6ICJUU1FMIg0KICAgIH0sDQogICAgIkNvbm5lY3Rpb25TdHJpbmdzIjogew0KICAgICAgIlNxbFNlcnZlciI6ICJTZXJ2ZXI9dGNwOm5vbnByb2RzcWxhY3VtZW4tcHJpbWFyeS5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0luaXRpYWwgQ2F0YWxvZz1kZXZlbG9wbWVudDtQZXJzaXN0IFNlY3VyaXR5IEluZm89RmFsc2U7VXNlciBJRD1zcWxhZG1pbjtQYXNzd29yZD1BMXMyZDNmNCM7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDsiLA0KICAgICAgIlJlZGlzIjogInJlZGlzLXJlZGlzLWNsdXN0ZXIucmVkaXMuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OSINCiAgICB9LA0KICAgICJFeHRlcm5hbElkZW50aXR5Q2xhaW1TZWN0aW9uIjogew0KICAgICAgIkZpcnN0TmFtZSI6IHsNCiAgICAgICAgIkV4dGVybmFsQ2xhaW1OYW1lIjogIiINCiAgICAgIH0sDQogICAgICAiTGFzdE5hbWUiOiB7DQogICAgICAgICJFeHRlcm5hbENsYWltTmFtZSI6ICIiDQogICAgICB9LA0KICAgICAgIkVtYWlsIjogew0KICAgICAgICAiRXh0ZXJuYWxDbGFpbU5hbWUiOiAiIg0KICAgICAgfSwNCiAgICAgICJNZW1iZXJPZiI6IHsNCiAgICAgICAgIkV4dGVybmFsQ2xhaW1OYW1lIjogIiINCiAgICAgIH0NCiAgICB9LA0KICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvblNldHRpbmdzIjogew0KICAgICAgIlVzZUthZmthIjogdHJ1ZSwNCiAgICAgICJLYWZrYUNhY2hlVG9waWMiOiAiIiwNCiAgICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsNCiAgICAgICAgIkJvb3RzdHJhcFNlcnZlcnMiOiAia2Fma2EtY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MiINCiAgICAgIH0sDQogICAgICAiQ2x1c3RlcklwQWRkcmVzc2VzIjogIiIsDQogICAgICAiQ2x1c3RlckNvbW11bmljYXRpb25Qcm90b2NvbCI6ICJodHRwIiwNCiAgICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvbkJhc2VVcmwiOiAie1BST1RPQ09MfTovL3tJUEFERFJFU1N9L0NpbmNoeSINCiAgICB9DQogIH0sDQogICJMb2dnaW5nIjogew0KICAgICJMb2dMZXZlbCI6IHsNCiAgICAgICJEZWZhdWx0IjogIkRlYnVnIg0KICAgIH0NCiAgfSwNCiAgIlNlcmlsb2ciOiB7DQogICAgIk1pbmltdW1MZXZlbCI6IHsNCiAgICAgICJEZWZhdWx0IjogIkRlYnVnIiwNCgkgICJPdmVycmlkZSI6IHsNCgkJIk1pY3Jvc29mdCI6ICJXYXJuaW5nIiwNCgkJIk1pY3Jvc29mdC5Ib3N0aW5nLkxpZmV0aW1lIjogIkluZm9ybWF0aW9uIg0KCSAgfQ0KICAgIH0sDQogICAgIldyaXRlVG8iOiBbDQogICAgICB7DQogICAgICAgICJOYW1lIjogIkNvbnNvbGUiLA0KICAgICAgICAiQXJncyI6IHsNCiAgICAgICAgICAiZm9ybWF0dGVyIjogIlNlcmlsb2cuRm9ybWF0dGluZy5Db21wYWN0LkNvbXBhY3RKc29uRm9ybWF0dGVyLCBTZXJpbG9nLkZvcm1hdHRpbmcuQ29tcGFjdCINCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIF0NCiAgfQ0KfQ==
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: idp-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-idp-app
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: DestinationRule
    name: idp-destinationrule
  patch: |-
    - op: replace
      path: /spec/trafficPolicy/loadBalancer/consistentHash/httpCookie/name
      value: development-idp-canary