apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/idp
namespace: development
commonLabels:
  app: idp
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: idp-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.idp:v5.4.0
    - op: add
      path: /spec/template/spec/volumes/-
      value: 
        name: idp-volume-redis-password
        secret:
          secretName: redis-redis-cluster
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: 
        name: idp-volume-redis-password
        readOnly: true
        mountPath: "/usr/share/redis/redis-redis-cluster"
#    - op: replace
#      path: /spec/template/spec/volumes/0
#      value:
#        name: idp-volume-appsettings
#        csi:
#          driver: secrets-store.csi.k8s.io
#          readOnly: true
#          volumeAttributes:
#            secretProviderClass: "idp-secret-appsettings"
- target:
    group: secrets-store.csi.x-k8s.io
    version: v1
    kind: SecretProviderClass
    name: idp-secret-appsettings
  patch: |-
    - op: replace
      path: /spec/parameters
      value: 
        objects:  |
          - objectName: "idp-secret-appsettings-development"
            objectType: "secretsmanager"
            jmesPath:
            - path: idpsecretappsettings
              objectAlias: appsettings.json
- target:
    version: v1
    kind: Secret
    name: idp-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ewogICJDb25maWdTZXR0aW5ncyI6IHsKICAgICJBcHBTZXR0aW5ncyI6IHsKICAgICAgIkNpbmNoeVVyaSI6ICJodHRwOi8vMjAuMTIxLjkyLjE3OSIsCiAgICAgICJDZXJ0aWZpY2F0ZVBhdGgiOiAiL2FwcC9jaW5jaHlpZGVudGl0eXNydi5wZngiLAogICAgICAiQ2VydGlmaWNhdGVQYXNzd29yZCI6ICIiLAogICAgICAiU0FNTENsaWVudEVudGl0eUlkIjogIiIsCiAgICAgICJTQU1MSURQRW50aXR5SWQiOiAiIiwKICAgICAgIlNBTUxNZXRhZGF0YVhtbFBhdGgiOiAiIiwKICAgICAgIlNBTUxTU09TZXJ2aWNlVVJMIjogIiIsCiAgICAgICJTQU1MRW5jcnlwdGVkQ2VydGlmaWNhdGVQYXRoIjogIiIsCiAgICAgICJTQU1MRW5jcnlwdGVkQ2VydGlmaWNhdGVQYXNzd29yZCI6ICIiLAogICAgICAiU0FNTFNpZ25DZXJ0aWZpY2F0ZVBhdGgiOiAiIiwKICAgICAgIlNBTUxTaWduQ2VydGlmaWNhdGVQYXNzd29yZCI6ICIiLAogICAgICAiQWNzVVJMTW9kdWxlIjogIiIsCiAgICAgICJTdHNQdWJsaWNPcmlnaW5VcmkiOiAiaHR0cDovLzIwLjEyMS45Mi4xNzkvaWRwIiwKICAgICAgIk1heFJlcXVlc3RIZWFkZXJzVG90YWxTaXplIjogNjU1MzYsCiAgICAgICJNYXhSZXF1ZXN0QnVmZmVyU2l6ZSI6IDY1NTM2LAogICAgICAiTWF4UmVxdWVzdEJvZHlTaXplIjogLTEsCiAgICAgICJNYWNoaW5lS2V5WG1sIjogIiIsCiAgICAgICJEcEFwaUtleVJpbmdQYXRoIjogIiIsCiAgICAgICJUbHNWZXJzaW9uIjogIjEuMiIsCiAgICAgICJDaW5jaHlBY2Nlc3NUb2tlbkxpZmV0aW1lIjogIjw8Y2luY2h5X3Nlc3Npb25fdGltZW91dD4+IiwKICAgICAgIkRhdGFDaGFuZ2VDYWxsYmFja1RpbWVvdXQiOiA3LAogICAgICAiUmVmcmVzaENhY2hlVGltZUluTWluIjogMTAsCiAgICAgICJEZWZhdWx0RXhwaXJhdGlvbkNhY2hlVGltZUluTWluIjogMzYwLAogICAgICAiREJUeXBlIjogIlRTUUwiCiAgICB9LAogICAgIkNvbm5lY3Rpb25TdHJpbmdzIjogewogICAgICAiU3FsU2VydmVyIjogIlNlcnZlcj10Y3A6bm9ucHJvZHNxbGFjdW1lbi1wcmltYXJ5LmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPWRldmVsb3BtZW50O1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPXNxbGFkbWluO1Bhc3N3b3JkPUExczJkM2Y0IztNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOyIsCiAgICAgICJSZWRpcyI6ICJyZWRpcy1yZWRpcy1jbHVzdGVyLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkiCiAgICB9LAogICAgIkV4dGVybmFsSWRlbnRpdHlDbGFpbVNlY3Rpb24iOiB7CiAgICAgICJGaXJzdE5hbWUiOiB7CiAgICAgICAgIkV4dGVybmFsQ2xhaW1OYW1lIjogIiIKICAgICAgfSwKICAgICAgIkxhc3ROYW1lIjogewogICAgICAgICJFeHRlcm5hbENsYWltTmFtZSI6ICIiCiAgICAgIH0sCiAgICAgICJFbWFpbCI6IHsKICAgICAgICAiRXh0ZXJuYWxDbGFpbU5hbWUiOiAiIgogICAgICB9LAogICAgICAiTWVtYmVyT2YiOiB7CiAgICAgICAgIkV4dGVybmFsQ2xhaW1OYW1lIjogIiIKICAgICAgfQogICAgfSwKICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvblNldHRpbmdzIjogewogICAgICAiVXNlS2Fma2EiOiB0cnVlLAogICAgICAiS2Fma2FDYWNoZVRvcGljIjogIiIsCiAgICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsKICAgICAgICAiQm9vdHN0cmFwU2VydmVycyI6ICJrYWZrYS1jbHVzdGVyLWthZmthLWJvb3RzdHJhcC5rYWZrYS5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyIgogICAgICB9LAogICAgICAiQ2x1c3RlcklwQWRkcmVzc2VzIjogIiIsCiAgICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvblByb3RvY29sIjogImh0dHAiLAogICAgICAiQ2x1c3RlckNvbW11bmljYXRpb25CYXNlVXJsIjogIntQUk9UT0NPTH06Ly97SVBBRERSRVNTfS9DaW5jaHkiCiAgICB9CiAgfSwKICAiTG9nZ2luZyI6IHsKICAgICJMb2dMZXZlbCI6IHsKICAgICAgIkRlZmF1bHQiOiAiRGVidWciCiAgICB9CiAgfSwKICAiU2VyaWxvZyI6IHsKICAgICJNaW5pbXVtTGV2ZWwiOiB7CiAgICAgICJEZWZhdWx0IjogIkRlYnVnIiwKCSAgIk92ZXJyaWRlIjogewoJCSJNaWNyb3NvZnQiOiAiV2FybmluZyIsCgkJIk1pY3Jvc29mdC5Ib3N0aW5nLkxpZmV0aW1lIjogIkluZm9ybWF0aW9uIgoJICB9CiAgICB9LAogICAgIldyaXRlVG8iOiBbCiAgICAgIHsKICAgICAgICAiTmFtZSI6ICJDb25zb2xlIiwKICAgICAgICAiQXJncyI6IHsKICAgICAgICAgICJmb3JtYXR0ZXIiOiAiU2VyaWxvZy5Gb3JtYXR0aW5nLkNvbXBhY3QuQ29tcGFjdEpzb25Gb3JtYXR0ZXIsIFNlcmlsb2cuRm9ybWF0dGluZy5Db21wYWN0IgogICAgICAgIH0KICAgICAgfQogICAgXQogIH0KfQ==
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: idp-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-idp-app
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: DestinationRule
    name: idp-destinationrule
  patch: |-
    - op: replace
      path: /spec/trafficPolicy/loadBalancer/consistentHash/httpCookie/name
      value: development-idp-canary
