apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: <environment>-datachangenotifications
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 100
  replicas: 3
  config:
    retention.ms: 86400000
    segment.bytes: 524288000