apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/event-listener
namespace: development
commonLabels:
  app: event-listener
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: event-listener-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.event-listener:v5.1.0
    - op: replace
      path: /spec/template/spec/containers/0/env/0/name
      value: development-EventListener_Node_Hostname
    - op: replace
      path: /spec/template/spec/containers/0/env/1/name
      value: development-EventListener_Node_Port
    - op: replace
      path: /spec/template/spec/containers/0/env/2/name
      value: development-EventListener_Node_Protocol
    - op: add
      path: /spec/template/spec/volumes/-
      value: 
        name: event-listener-volume-redis-password
        secret:
          secretName: redis-redis-cluster
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: 
        name: event-listener-volume-redis-password
        readOnly: true
        mountPath: "/usr/share/redis/redis-redis-cluster"
- target:
    version: v1
    kind: Secret
    name: event-listener-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ew0KICAgICJDaW5jaHlDbGllbnRTZXR0aW5ncyI6IHsNCiAgICAgICAgIlVybCI6ICJodHRwczovL2NpbmNoeS5tZW51Y2l0eWFwcC5hbSIsDQogICAgICAgICJVc2VybmFtZSI6ICIiLA0KICAgICAgICAiUGFzc3dvcmQiOiAiIiAgDQogICAgfSwNCiAgICAiQXBwU2V0dGluZ3MiOiB7DQogICAgIkdldE5ld0xpc3RlbmVyQ29uZmlnc0ludGVydmFsIjogIjYwIiwNCiAgICAiU3RhdGVGaWxlTG9jYXRpb24iOiAiL2FwcC9kYXRhL2V2ZW50LWxpc3RlbmVyL3N0YXRlZmlsZXMiLA0KICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsNCiAgICAgICJCb290c3RyYXBTZXJ2ZXJzIjogImthZmthLWNsdXN0ZXIta2Fma2EtYm9vdHN0cmFwLmthZmthLnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIiDQogICAgfQ0KICB9LA0KICAiQ29ubmVjdGlvblN0cmluZ3MiOiB7DQogICAgIlNxbFNlcnZlciI6ICIiLA0KICAgICJSZWRpcyI6ICJyZWRpcy1yZWRpcy1jbHVzdGVyLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkiDQogIH0sDQogICJDbHVzdGVyQ29uZmlndXJhdGlvbiI6IHsNCiAgICAibG93ZXJFbGVjdGlvblRpbWVvdXQiOiAxNTAsDQogICAgInVwcGVyRWxlY3Rpb25UaW1lb3V0IjogMzAwLA0KICAgICJyZXF1ZXN0VGltZW91dCI6ICIwMDowMTowMCIsDQogICAgImtlZXBBbGl2ZVRpbWVvdXQiOiAiMDA6MDI6MDAiDQogIH0sDQogICJBbGxvd2VkSG9zdHMiOiAiKiIsDQogICJTZXJpbG9nIjogew0KICAgICJNaW5pbXVtTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJEZWJ1ZyIsDQogICAgICAiT3ZlcnJpZGUiOiB7DQogICAgICAgICJNaWNyb3NvZnQiOiAiV2FybmluZyIsDQogICAgICAgICJTeXN0ZW0uTmV0IjogIldhcm5pbmciLA0KICAgICAgICAiTWljcm9zb2Z0Lkhvc3RpbmcuTGlmZXRpbWUiOiAiSW5mb3JtYXRpb24iLA0KICAgICAgICAiRG90TmV4dC5OZXQuQ2x1c3RlciI6ICJJbmZvcm1hdGlvbiIsDQogICAgICAgICJDaW5jaHkuQ29tbW9uLkNsdXN0ZXJpbmcuQ2x1c3RlckNvbmZpZ3VyYXRpb25Qcm92aWRlciI6ICJJbmZvcm1hdGlvbiINCiAgICAgIH0NCiAgICB9LA0KICAgICJXcml0ZVRvIjogWw0KICAgICAgew0KICAgICAgICAiTmFtZSI6ICJDb25zb2xlIiwNCiAgICAgICAgIkFyZ3MiOiB7DQogICAgICAgICAgImZvcm1hdHRlciI6ICJTZXJpbG9nLkZvcm1hdHRpbmcuQ29tcGFjdC5Db21wYWN0SnNvbkZvcm1hdHRlciwgU2VyaWxvZy5Gb3JtYXR0aW5nLkNvbXBhY3QiDQogICAgICAgIH0NCiAgICAgIH0NCiAgICBdDQogIH0NCn0=
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: event-listener-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-event-listener-app
- target:
    group: kafka.strimzi.io
    version: v1beta2
    kind: KafkaTopic
    name: <environment>-realtimedatasynctopic
  patch: |-
    - op: replace
      path: /metadata/name
      value: development-realtimedatasynctopic
    - op: replace
      path: /metadata/namespace
      value: kafka
