apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: idp-secret-appsettings
spec:
  provider: aws
  parameters:                    # provider-specific parameters
    objects:  |
      - objectName: "idp-secret-appsettings"
        objectType: "secretsmanager"
        jmesPath:
        - path: idpsecretappsettings
          objectAlias: appsettings.json