apiVersion: v1
kind: Namespace
metadata:
  name: ns-ecr-renew
  labels:
    name: ns-ecr-renew
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ns-ecr-renew
  name: svc-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-ecr-renew
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "delete", "get", "list"]
- apiGroups: ["apps"]
  resources: ["namespaces"]
  verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: ns-ecr-renew
  name: rb-ecr-renew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: ns-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: ns-ecr-renew
  name: development # One or more Cluster Role Binding based on environment name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: ns-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: ns-ecr-renew
  name: qa1 # One or more Cluster Role Binding based on environment name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: ns-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: ns-ecr-renew
  name: qa2 # One or more Cluster Role Binding based on environment name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: ns-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: ns-ecr-renew
  name: staging # One or more Cluster Role Binding based on environment name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: ns-ecr-renew