apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/web
namespace: development
commonLabels:
  app: web
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.web:v5.1.0
    - op: add
      path: /spec/template/spec/volumes/-
      value: 
        name: web-volume-redis-password
        secret:
          secretName: redis-redis-cluster
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: 
        name: web-volume-redis-password
        readOnly: true
        mountPath: "/usr/share/redis/redis-redis-cluster"
- target:
    version: v1
    kind: Secret
    name: web-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ew0KICAiQ29uZmlnU2V0dGluZ3MiOiB7DQogICAgIkFwcFNldHRpbmdzIjogew0KICAgICAgIlN0c0F1dGhvcml0eVVyaSI6ICJodHRwczovLy9pZHAiLA0KICAgICAgIkFsbG93TG9nRmlsZURvd25sb2FkIjogZmFsc2UsDQogICAgICAiTG9nRGlyZWN0b3J5UGF0aCI6ICIiLA0KICAgICAgIlNTT0xvZ1BhdGgiOiAiIiwNCiAgICAgICJVc2VIdHRwcyI6IHRydWUsDQogICAgICAiSHN0c01heEFnZSI6IDI1OTIwMDAsDQogICAgICAiSHN0c0luY2x1ZGVTdWJEb21haW5zIjogZmFsc2UsDQogICAgICAiSHN0c1ByZWxvYWQiOiBmYWxzZSwNCiAgICAgICJUbHNWZXJzaW9uIjogIjEuMiIsDQogICAgICAiUm91dGVEZWJ1Z2dlckVuYWJsZWQiOiBmYWxzZSwNCiAgICAgICJSZWZyZXNoQ2FjaGVUaW1lSW5NaW4iOiAxMCwNCiAgICAgICJEZWZhdWx0RXhwaXJhdGlvbkNhY2hlVGltZUluTWluIjogMzYwLA0KICAgICAgIkRCVHlwZSI6ICJUU1FMIiwNCiAgICAgICJTdG9yYWdlVHlwZSI6ICI8PHdlYl9zdG9yYWdlX3R5cGU+PiINCiAgICB9LA0KICAgICJSZXZlcnNlUHJveHlTZXR0aW5ncyI6IHsNCiAgICAgICJJc0VuYWJsZWQiOiB0cnVlLA0KICAgICAgIkJhc2VQYXRoIjogIiIsDQogICAgICAiVXNlSHR0cHMiOiB0cnVlDQogICAgfSwNCiAgICAiQ29ubmVjdGlvblN0cmluZ3MiOiB7DQogICAgICAiU3FsU2VydmVyIjogIlNlcnZlcj10Y3A6bm9ucHJvZHNxbGFjdW1lbi1wcmltYXJ5LmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPWRldmVsb3BtZW50O1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPXNxbGFkbWluO1Bhc3N3b3JkPUExczJkM2Y0IztNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOyIsDQogICAgICAiUmVkaXMiOiAicmVkaXMtcmVkaXMtY2x1c3Rlci5yZWRpcy5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5Ig0KICAgIH0sDQogICAgIkF6dXJlQmxvYlN0b3JhZ2VTZXR0aW5ncyI6IHsNCiAgICAgICJDb25uZWN0aW9uU3RyaW5nIjogIjw8d2ViX2F6dXJlX2Jsb2Jfc3RvcmFnZV9jb25uX3N0cj4+IiwNCiAgICAgICJDb250YWluZXIiOiAiPDx3ZWJfc3RvcmFnZV9jb250YWluZXJfbmFtZT4+IiwNCiAgICAgICJCYXNlUGF0aCI6ICI8PHdlYl9zdG9yYWdlX2Jhc2VwYXRoPj4iDQogICAgfSwNCiAgICAiUzNTZXR0aW5ncyI6IHsNCiAgICAgICJBY2Nlc3NLZXkiOiAiPDx3ZWJfczNfYWNjZXNzX2tleT4+IiwNCiAgICAgICJTZWNyZXRBY2Nlc3NLZXkiOiAiPDx3ZWJfczNfc2VjcmV0X2FjY2Vzc19rZXk+PiIsDQogICAgICAiUmVnaW9uIjogIjw8YXdzX3JlZ2lvbj4+IiwNCiAgICAgICJCdWNrZXQiOiAiPDxjaW5jaHlfd2ViX3MzX2J1Y2tldD4+IiwNCiAgICAgICJCYXNlUGF0aCI6ICI8PHdlYl9zdG9yYWdlX2Jhc2VwYXRoPj4iLA0KICAgICAgIlNlcnZpY2VVUkwiOiAiPDx3ZWJfczNfc2VydmljZV91cmw+PiINCiAgICB9LA0KICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvblNldHRpbmdzIjogew0KICAgICAgIlVzZUthZmthIjogdHJ1ZSwNCiAgICAgICJLYWZrYUNhY2hlVG9waWMiOiAiIiwNCiAgICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsNCiAgICAgICAgIkJvb3RzdHJhcFNlcnZlcnMiOiAia2Fma2EtY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MiINCiAgICAgIH0sDQogICAgICAiQ2x1c3RlcklwQWRkcmVzc2VzIjogIiIsDQogICAgICAiQ2x1c3RlckNvbW11bmljYXRpb25Qcm90b2NvbCI6ICJodHRwIiwNCiAgICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvbkJhc2VVcmwiOiAie1BST1RPQ09MfTovL3tJUEFERFJFU1N9L0NpbmNoeSINCiAgICB9DQogIH0sDQogICJMb2dnaW5nIjogew0KICAgICJNaW5pbXVtTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJEZWJ1ZyIsDQogICAgICAiT3ZlcnJpZGUiOiB7DQoJCSJNaWNyb3NvZnQiOiAiV2FybmluZyIsDQoJCSJNaWNyb3NvZnQuSG9zdGluZy5MaWZldGltZSI6ICJJbmZvcm1hdGlvbiINCgkgIH0NCiAgICB9DQogIH0sDQogICJTZXJpbG9nIjogew0KICAgICJNaW5pbXVtTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJEZWJ1ZyIsDQoJICAiT3ZlcnJpZGUiOiB7DQoJCSJNaWNyb3NvZnQiOiAiV2FybmluZyIsDQoJCSJNaWNyb3NvZnQuSG9zdGluZy5MaWZldGltZSI6ICJJbmZvcm1hdGlvbiINCgkgIH0NCiAgICB9LA0KICAgICJXcml0ZVRvIjogWw0KICAgICAgew0KICAgICAgICAiTmFtZSI6ICJDb25zb2xlIiwNCiAgICAgICAgIkFyZ3MiOiB7DQogICAgICAgICAgImZvcm1hdHRlciI6ICJTZXJpbG9nLkZvcm1hdHRpbmcuQ29tcGFjdC5Db21wYWN0SnNvbkZvcm1hdHRlciwgU2VyaWxvZy5Gb3JtYXR0aW5nLkNvbXBhY3QiDQogICAgICAgIH0NCiAgICAgIH0NCiAgICBdDQogIH0sDQogICJBbGxvd2VkSG9zdHMiOiAiKiINCn0=
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: web-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-web-app
- target:
    group: kafka.strimzi.io
    version: v1beta2
    kind: KafkaTopic
    name: <environment>-datachangenotifications
  patch: |-
    - op: replace
      path: /metadata/name
      value: development-datachangenotifications
    - op: replace
      path: /metadata/namespace
      value: kafka
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: DestinationRule
    name: web-destinationrule
  patch: |-
    - op: replace
      path: /spec/trafficPolicy/loadBalancer/consistentHash/httpCookie/name
      value: development-web-canary