apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/web
namespace: development
commonLabels:
  app: web
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.web:v5.4.0
    - op: add
      path: /spec/template/spec/volumes/-
      value: 
        name: web-volume-redis-password
        secret:
          secretName: redis-redis-cluster
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: 
        name: web-volume-redis-password
        readOnly: true
        mountPath: "/usr/share/redis/redis-redis-cluster"
#    - op: replace
#      path: /spec/template/spec/volumes/0
#      value:
#        name: web-volume-appsettings
#        csi:
#          driver: secrets-store.csi.k8s.io
#          readOnly: true
#          volumeAttributes:
#            secretProviderClass: "web-secret-appsettings"
- target:
    group: secrets-store.csi.x-k8s.io
    version: v1
    kind: SecretProviderClass
    name: web-secret-appsettings
  patch: |-
    - op: replace
      path: /spec/parameters
      value: 
        objects:  |
          - objectName: "web-secret-appsettings-development"
            objectType: "secretsmanager"
            jmesPath:
            - path: websecretappsettings
              objectAlias: appsettings.json
- target:
    version: v1
    kind: Secret
    name: web-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ewogICJDb25maWdTZXR0aW5ncyI6IHsKICAgICJBcHBTZXR0aW5ncyI6IHsKICAgICAgIlN0c0F1dGhvcml0eVVyaSI6ICJodHRwOi8vMjAuMTI0Ljc3LjE2MS9pZHAiLAogICAgICAiQWxsb3dMb2dGaWxlRG93bmxvYWQiOiBmYWxzZSwKICAgICAgIkxvZ0RpcmVjdG9yeVBhdGgiOiAiIiwKICAgICAgIlNTT0xvZ1BhdGgiOiAiIiwKICAgICAgIlVzZUh0dHBzIjogZmFsc2UsCiAgICAgICJIc3RzTWF4QWdlIjogMjU5MjAwMCwKICAgICAgIkhzdHNJbmNsdWRlU3ViRG9tYWlucyI6IGZhbHNlLAogICAgICAiSHN0c1ByZWxvYWQiOiBmYWxzZSwKICAgICAgIlRsc1ZlcnNpb24iOiAiMS4yIiwKICAgICAgIlJvdXRlRGVidWdnZXJFbmFibGVkIjogZmFsc2UsCiAgICAgICJSZWZyZXNoQ2FjaGVUaW1lSW5NaW4iOiAxMCwKICAgICAgIkRlZmF1bHRFeHBpcmF0aW9uQ2FjaGVUaW1lSW5NaW4iOiAzNjAsCiAgICAgICJEQlR5cGUiOiAiVFNRTCIsCiAgICAgICJTdG9yYWdlVHlwZSI6ICJBenVyZUJsb2JTdG9yYWdlIiwKICAgICAgIk1heFJlcXVlc3RCb2R5U2l6ZSIgOiAxMDczNzQxODI0CiAgICB9LAogICAgIlJldmVyc2VQcm94eVNldHRpbmdzIjogewogICAgICAiSXNFbmFibGVkIjogdHJ1ZSwKICAgICAgIkJhc2VQYXRoIjogIiIsCiAgICAgICJVc2VIdHRwcyI6IGZhbHNlCiAgICB9LAogICAgIkNvbm5lY3Rpb25TdHJpbmdzIjogewogICAgICAiU3FsU2VydmVyIjogIlNlcnZlcj10Y3A6bm9ucHJvZHNxbGFjdW1lbi1wcmltYXJ5LmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPWRldmVsb3BtZW50O1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPXNxbGFkbWluO1Bhc3N3b3JkPUExczJkM2Y0IztNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOyIsCiAgICAgICJSZWRpcyI6ICJyZWRpcy1yZWRpcy1jbHVzdGVyLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkiCiAgICB9LAogICAgIkF6dXJlQmxvYlN0b3JhZ2VTZXR0aW5ncyI6IHsKICAgICAgIkNvbm5lY3Rpb25TdHJpbmciOiAiRGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWFjdW1lbmNpbmNoeW5vbnByb2Q7QWNjb3VudEtleT1CbjZJak1zM1B2TTNRYk40UUc3MDMyLzZDR3AraTh0aEMrR05WVXVYTm1ITjN1bVBlMjBHOFhOVElBR3VjYU56TkRVQ2R2RGVQa044K0FTdGFqSXkwZz09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQiLAogICAgICAiQ29udGFpbmVyIjogIm5vbnByb2Qtd2ViIiwKICAgICAgIkJhc2VQYXRoIjogImRldmVsb3BtZW50L2NpbmNoeXdlYiIKICAgIH0sCiAgICAiUzNTZXR0aW5ncyI6IHsKICAgICAgIkFjY2Vzc0tleSI6ICI8PGNpbmNoeV9zM19hY2Nlc3Nfa2V5Pj4iLAogICAgICAiU2VjcmV0QWNjZXNzS2V5IjogIjw8Y2luY2h5X3MzX3NlY3JldF9hY2Nlc3Nfa2V5Pj4iLAogICAgICAiUmVnaW9uIjogIjw8YXdzX3JlZ2lvbj4+IiwKICAgICAgIkJ1Y2tldCI6ICI8PGNpbmNoeV9zM19idWNrZXQ+PiIsCiAgICAgICJCYXNlUGF0aCI6ICJkZXZlbG9wbWVudC9jaW5jaHl3ZWIiLAogICAgICAiU2VydmljZVVSTCI6ICI8PGNpbmNoeV9zM19zZXJ2aWNlX3VybD4+IgogICAgfSwKICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvblNldHRpbmdzIjogewogICAgICAiVXNlS2Fma2EiOiB0cnVlLAogICAgICAiS2Fma2FDYWNoZVRvcGljIjogIiIsCiAgICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsKICAgICAgICAiQm9vdHN0cmFwU2VydmVycyI6ICJrYWZrYS1jbHVzdGVyLWthZmthLWJvb3RzdHJhcC5rYWZrYS5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyIgogICAgICB9LAogICAgICAiQ2x1c3RlcklwQWRkcmVzc2VzIjogIiIsCiAgICAgICJDbHVzdGVyQ29tbXVuaWNhdGlvblByb3RvY29sIjogImh0dHAiLAogICAgICAiQ2x1c3RlckNvbW11bmljYXRpb25CYXNlVXJsIjogIntQUk9UT0NPTH06Ly97SVBBRERSRVNTfS9DaW5jaHkiCiAgICB9CiAgfSwKICAiTG9nZ2luZyI6IHsKICAgICJNaW5pbXVtTGV2ZWwiOiB7CiAgICAgICJEZWZhdWx0IjogIkRlYnVnIiwKICAgICAgIk92ZXJyaWRlIjogewoJCSAgICAiTWljcm9zb2Z0IjogIldhcm5pbmciLAoJCSAgICAiTWljcm9zb2Z0Lkhvc3RpbmcuTGlmZXRpbWUiOiAiSW5mb3JtYXRpb24iLAogICAgICAgICJDaW5jaHkuV2ViLkF1dGhlbnRpY2F0aW9uLkhhbmRsZXJzLkFub255bW91c0F1dGhlbnRpY2F0aW9uSGFuZGxlciI6ICJJbmZvcm1hdGlvbiIKCSAgICB9CiAgICB9CiAgfSwKICAiU2VyaWxvZyI6IHsKICAgICJNaW5pbXVtTGV2ZWwiOiB7CiAgICAgICJEZWZhdWx0IjogIkRlYnVnIiwKCSAgICAiT3ZlcnJpZGUiOiB7CgkJICAgICJNaWNyb3NvZnQiOiAiV2FybmluZyIsCgkJICAgICJNaWNyb3NvZnQuSG9zdGluZy5MaWZldGltZSI6ICJJbmZvcm1hdGlvbiIsCiAgICAgICAgIkNpbmNoeS5XZWIuQXV0aGVudGljYXRpb24uSGFuZGxlcnMuQW5vbnltb3VzQXV0aGVudGljYXRpb25IYW5kbGVyIjogIkluZm9ybWF0aW9uIgoJICAgIH0KICAgIH0sCiAgICAiV3JpdGVUbyI6IFsKICAgICAgewogICAgICAgICJOYW1lIjogIkNvbnNvbGUiLAogICAgICAgICJBcmdzIjogewogICAgICAgICAgImZvcm1hdHRlciI6ICJTZXJpbG9nLkZvcm1hdHRpbmcuQ29tcGFjdC5Db21wYWN0SnNvbkZvcm1hdHRlciwgU2VyaWxvZy5Gb3JtYXR0aW5nLkNvbXBhY3QiCiAgICAgICAgfQogICAgICB9CiAgICBdCiAgfSwKICAiQWxsb3dlZEhvc3RzIjogIioiCn0=
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: web-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-web-app
- target:
    group: kafka.strimzi.io
    version: v1beta2
    kind: KafkaTopic
    name: <environment>-datachangenotifications
  patch: |-
    - op: replace
      path: /metadata/name
      value: development-datachangenotifications
    - op: replace
      path: /metadata/namespace
      value: kafka
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: DestinationRule
    name: web-destinationrule
  patch: |-
    - op: replace
      path: /spec/trafficPolicy/loadBalancer/consistentHash/httpCookie/name
      value: development-web-canary
