apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: forms-logging-flow
spec:
  filters:
    - tag_normaliser: {}
  match:
    - select:
        labels:
          name: forms-app
  localOutputRefs:
    - forms-logging-stdout
