apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: forms-secret-config
spec:
  provider: aws
  parameters:                    # provider-specific parameters
    objects:  |
      - objectName: "forms-secret-config"
        objectType: "secretsmanager"
        jmesPath:
        - path: formssecretconfig
          objectAlias: appsettings.json