apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/maintenance-cli
namespace: development
commonLabels:
  app: maintenance-cli
  env: development
patchesJson6902:
- target:
    group: batch
    version: v1
    kind: CronJob
    name: maintenance-cli-app
  patch: |-
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.maintenance.cli:v5.1.0
    - op: add
      path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
      value:
        name: CINCHY_INSTANCE_URL
        value: cinchy.menucityapp.am
- target:
    version: v1
    kind: Secret
    name: maintenance-cli-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ewogICJTZXJpbG9nIjogewogICAgIk1pbmltdW1MZXZlbCI6IHsKICAgICAgIkRlZmF1bHQiOiAiRGVidWciLAogICAgICAiT3ZlcnJpZGUiOiB7CiAgICAgICAgIk1pY3Jvc29mdCI6ICJXYXJuaW5nIiwKICAgICAgICAiU3lzdGVtLk5ldCI6ICJXYXJuaW5nIiwKICAgICAgICAiQ2luY2h5LkNvbW1vbi5FbmNyeXB0aW9uLkVuY3J5cHRpb25TZXJ2aWNlIjogIkZhdGFsIgogICAgICB9CiAgICB9LAogICAgIldyaXRlVG8iOiBbCiAgICAgIHsKICAgICAgICAiTmFtZSI6ICJDb25zb2xlIiwKICAgICAgICAiQXJncyI6IHsKICAgICAgICAgICJmb3JtYXR0ZXIiOiAiU2VyaWxvZy5Gb3JtYXR0aW5nLkNvbXBhY3QuQ29tcGFjdEpzb25Gb3JtYXR0ZXIsIFNlcmlsb2cuRm9ybWF0dGluZy5Db21wYWN0IgogICAgICAgIH0KICAgICAgfQogICAgXQogIH0KfQ==
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: maintenance-cli-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-maintenance-cli-app