apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: maintenance-cli-logging-flow
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
  match:
    - select:
        labels:
          name: maintenance-cli-app
  localOutputRefs:
    - maintenance-cli-logging-stdout
