apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: maintenance-cli-secret-appsettings
spec:
  provider: aws
  parameters:                    # provider-specific parameters
    objects:  |
      - objectName: "maintenance-cli-secret-appsettings"
        objectType: "secretsmanager"
        jmesPath:
        - path: maintenanceclisecretappsettings
          objectAlias: appsettings.json