apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/worker
namespace: development
commonLabels:
  app: worker
  env: development
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: worker-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 658484148438.dkr.ecr.ca-central-1.amazonaws.com/cinchy.connections.worker:v5.4.0
#    - op: replace
#      path: /spec/template/spec/volumes/0
#      value:
#        name: worker-volume-appsettings
#        csi:
#          driver: secrets-store.csi.k8s.io
#          readOnly: true
#          volumeAttributes:
#            secretProviderClass: "worker-secret-appsettings"
- target:
    group: secrets-store.csi.x-k8s.io
    version: v1
    kind: SecretProviderClass
    name: worker-secret-appsettings
  patch: |-
    - op: replace
      path: /spec/parameters
      value: 
        objects:  |
          - objectName: "worker-secret-appsettings-development"
            objectType: "secretsmanager"
            jmesPath:
            - path: workersecretappsettings
              objectAlias: appsettings.json
- target:
    version: v1
    kind: Secret
    name: worker-secret-appsettings
  patch: |-
    - op: replace
      path: /data/appsettings.json
      value: ewogICAgIkNpbmNoeUNsaWVudFNldHRpbmdzIjogewogICAgICAgICJVcmwiOiAiaHR0cDovLzIwLjExOS4xMTUuMTY5IiwKICAgICAgICAiVXNlcm5hbWUiOiAiIiwKICAgICAgICAiUGFzc3dvcmQiOiAiIiAgCiAgICB9LAogICAgIkFwcFNldHRpbmdzIjogewogICAgIk1vZGVsIjogIkNpbmNoeSIsCiAgICAiVGVtcERpcmVjdG9yeSI6ICIvdG1wIiwKICAgICJUbHNWZXJzaW9uIjogIiIsCiAgICAiV29ya2VyVGhyZWFkQ291bnQiOiAiMTIiLAogICAgIldvcmtlckJhdGNoU2l6ZUxpbWl0IjogIjIwIiwKICAgICJLYWZrYUNsaWVudENvbmZpZyI6IHsKICAgICAgIkJvb3RzdHJhcFNlcnZlcnMiOiAia2Fma2EtY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MiIKICAgIH0sCiAgICAiS2Fma2FNZXNzYWdlQ29uc3VtZU1zTGltaXQiOiAxMDAsCiAgICAiS2Fma2FNZXNzYWdlQmF0Y2hDb25zdW1lTXNMaW1pdCI6IDIwMAogIH0sCiAgIkNvbm5lY3Rpb25TdHJpbmdzIjogewogICAgIlNxbFNlcnZlciI6ICIiCiAgfSwKICAiU2VyaWxvZyI6IHsKICAgICJNaW5pbXVtTGV2ZWwiOiB7CiAgICAgICJEZWZhdWx0IjogIkRlYnVnIiwKICAgICAgIk92ZXJyaWRlIjogewogICAgICAgICJNaWNyb3NvZnQiOiAiV2FybmluZyIsCiAgICAgICAgIlN5c3RlbS5OZXQiOiAiV2FybmluZyIKICAgICAgfQogICAgfSwKICAgICJXcml0ZVRvIjogWwogICAgICB7CiAgICAgICAgIk5hbWUiOiAiQ29uc29sZSIsCiAgICAgICAgIkFyZ3MiOiB7CiAgICAgICAgICAiZm9ybWF0dGVyIjogIlNlcmlsb2cuRm9ybWF0dGluZy5Db21wYWN0LkNvbXBhY3RKc29uRm9ybWF0dGVyLCBTZXJpbG9nLkZvcm1hdHRpbmcuQ29tcGFjdCIKICAgICAgICB9CiAgICAgIH0KICAgIF0KICB9Cn0=
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: worker-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: development-worker-app
