apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../platform_components/forms
namespace: <<namespace>>
commonLabels:
  app: forms
  env: <<namespace>>
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: forms-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: <<meta_forms_image_repo_uri>>:<<meta_forms_image_tag>>
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: forms-volume-config
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "forms-secret-config"
- target:
    group: secrets-store.csi.x-k8s.io
    version: v1
    kind: SecretProviderClass
    name: forms-secret-config
  patch: |-
    - op: replace
      path: /spec/parameters
      value: 
        objects:  |
          - objectName: "forms-secret-config-<<namespace>>"
            objectType: "secretsmanager"
            jmesPath:
            - path: formssecretconfig
              objectAlias: appsettings.json
- target:
    version: v1
    kind: Secret
    name: forms-secret-config
  patch: |-
    - op: replace
      path: /data/config.json
      value: <<meta_forms_config_json>>
- target:
    group: logging.banzaicloud.io
    version: v1beta1
    kind: Output
    name: forms-logging-stdout
  patch: |-
    - op: replace
      path: /spec/elasticsearch/index_name
      value: <<namespace>>-forms-app
