apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: connections-secret-config
spec:
  provider: aws
  parameters:                    # provider-specific parameters
    objects:  |
      - objectName: "connections-secret-config"
        objectType: "secretsmanager"
        jmesPath:
        - path: connectionssecretconfig
          objectAlias: config.json