apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: connections-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connections-app
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300